### ISSUE TITLE
User (applicant) qualification

### ISSUE THREAD

**Issue by fontvu** [troppdus/MyWorstJobApp#3]
Hello,

The applicant could upload his/her qualifications as well as personal documents. My understanding is the attribute represents these documents is *qualification* in the class user. If this is the case, what should the qualification display in the UI? Is it a single document i.e. master/bachelor's degree or CV or both?

**Comment by troppdus** [comment]
Sorry, we needed some time to discuss. 
We came to the conclusion that CV should be an extra property that is mandatory. In qualification should be the rest of the documents. 
To make it more clear, we thought document is an extra class with documentId, title and file. For the UI of a document it should show the name, but if you manage to do it, it would be cool if it is clickable. After clicking on the name, the PDF opens in the browser. (this should be doable because many sites use it, but I don't know how hard it is to implement)

**Comment by fontvu** [comment]
In that case, an additional class *document* will be added. The class will have the following attributes:
- documentID
- title
- file (or filePath)

The attribute *qualification* in applicant (user) will be *document* type.

**Comment by troppdus** [comment]
Yes, exactly.
